### ISSUE TITLE
Script file not found - 404

### ISSUE THREAD

**Issue by HamedMP** [jeanmidevacc/french-presidential-election-twitter-pov#1]
Hi Jean, 

Can you please share the python script you mentioned in the Kaggle dataset description?

**Comment by jeanmidevacc** [comment]
Sorry for the delay i upload the main files that i used to make the dataset.

I still have to improve the comments and add some other files (how to deal with the google trends file etc)

**Comment by HamedMP** [comment]
Thank you for uploading the code. 

1. How to schedule for getting the tweets every 20 minutes? 
2. How to connect to S3 bucket? By only the name? No auth code, etc is needed? 
3. I didn't completely understand the listening.py. Do you open a stream and print filtered tweets to the terminal? Can you explain a little bit the practical part how you did it? I think doing it by hand is a little bit messy. Did you use some codes/scripts to automate the process? (bash script, uploading to S3)

Again thank you for the dataset and the code.
